# Generated by Django 5.1.2 on 2024-11-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioSinistro',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('dispositivo', models.CharField(max_length=255)),
                ('foto_sinistro', models.URLField()),
                ('data_hora', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('id_sinistro', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enviodesinistro',
            },
        ),
        migrations.CreateModel(
            name='RegS',
            fields=[
                ('id_sinistro', models.AutoField(primary_key=True, serialize=False)),
                ('clima', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('luminosidade', models.CharField(blank=True, max_length=20, null=True)),
                ('data_hora', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'db_table': 'regs',
            },
        ),
    ]
