# Generated by Django 5.1.2 on 2024-11-23 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadbox_cloudapi_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regs',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='regs',
            name='longitude',
        ),
    ]
