# Generated by Django 5.1.2 on 2024-11-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadbox_cloudapi_app', '0002_remove_regs_latitude_remove_regs_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='regs',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='regs',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
