# Generated by Django 5.1.2 on 2024-12-14 01:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadbox_cloudapi_app', '0003_regs_latitude_regs_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviosinistro',
            name='id_sinistro',
        ),
        migrations.AlterField(
            model_name='regs',
            name='id_sinistro',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
